### ISSUE TITLE
 Incorrect clone link in readme

### ISSUE THREAD

**Issue by Sharpness-B** [linkedin-faq/quizzes-practice-app#2]
You might want to change 

[https://github.com/**Sharpness-B**/quizzes-practice-app.git](https://github.com/Sharpness-B/quizzes-practice-app.git)

to

[https://github.com/**linkedin-faq**/quizzes-practice-app.git](https://github.com/linkedin-faq/quizzes-practice-app.git)

in README.md

**Comment by Ebazhanov** [comment]
good catch, resolved!
